### ISSUE TITLE
Training Issue

### ISSUE THREAD

**Issue by abhisheksurya578** [TianzhongSong/C3D-keras#12]
Hello @TianzhongSong 

    generator_output = next(self._generator)
  File "/ds_data/C3D-keras-master/train_c3d.py", line 116, in generator_train_batch
    x_train, x_labels = process_batch(new_line[a:b],img_path,train=True)
  File "/ds_data/C3D-keras-master/train_c3d.py", line 71, in process_batch
    img = imgs[symbol + j]
IndexError: list index out of range

Traceback (most recent call last):
  File "/ds_data/C3D-keras-master/train_c3d.py", line 180, in <module>
    main()
  File "/ds_data/C3D-keras-master/train_c3d.py", line 171, in main
    validation_steps=val_samples // batch_size,verbose=None)
  File "/usr/local/lib/python3.5/dist-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/training.py", line 2011, in fit_generator
    generator_output = next(output_generator)
StopIteration

Process finished with exit code 1

help me to solve this error <3

**Comment by abhisheksurya578** [comment]
Hello @TianzhongSong

generator_output = next(self._generator)
File "/ds_data/C3D-keras-master/train_c3d.py", line 116, in generator_train_batch
x_train, x_labels = process_batch(new_line[a:b],img_path,train=True)
File "/ds_data/C3D-keras-master/train_c3d.py", line 71, in process_batch
img = imgs[symbol + j]
IndexError: list index out of range

Traceback (most recent call last):
File "/ds_data/C3D-keras-master/train_c3d.py", line 180, in 
main()
File "/ds_data/C3D-keras-master/train_c3d.py", line 171, in main
validation_steps=val_samples // batch_size,verbose=None)
File "/usr/local/lib/python3.5/dist-packages/keras/legacy/interfaces.py", line 87, in wrapper
return func(*args, **kwargs)
File "/usr/local/lib/python3.5/dist-packages/keras/engine/training.py", line 2011, in fit_generator
generator_output = next(output_generator)
StopIteration

Process finished with exit code 1

help me to solve this error <3
