### ISSUE TITLE
training issue

### ISSUE THREAD

**Issue by abhisheksurya578** [TianzhongSong/C3D-keras#13]
hi @TianzhongSong ,
                                                Using TensorFlow backend.
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input_1 (InputLayer)         (None, 112, 112, 16, 3)   0         
_________________________________________________________________
conv3d_1 (Conv3D)            (None, 112, 112, 16, 64)  5248      
_________________________________________________________________
max_pooling3d_1 (MaxPooling3 (None, 56, 56, 16, 64)    0         
_________________________________________________________________
conv3d_2 (Conv3D)            (None, 56, 56, 16, 128)   221312    
_________________________________________________________________
max_pooling3d_2 (MaxPooling3 (None, 28, 28, 8, 128)    0         
_________________________________________________________________
conv3d_3 (Conv3D)            (None, 28, 28, 8, 128)    442496    
_________________________________________________________________
max_pooling3d_3 (MaxPooling3 (None, 14, 14, 4, 128)    0         
_________________________________________________________________
conv3d_4 (Conv3D)            (None, 14, 14, 4, 256)    884992    
_________________________________________________________________
max_pooling3d_4 (MaxPooling3 (None, 7, 7, 2, 256)      0         
_________________________________________________________________
conv3d_5 (Conv3D)            (None, 7, 7, 2, 256)      1769728   
_________________________________________________________________
max_pooling3d_5 (MaxPooling3 (None, 4, 4, 1, 256)      0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 4096)              0         
_________________________________________________________________
dense_1 (Dense)              (None, 2048)              8390656   
_________________________________________________________________
dropout_1 (Dropout)          (None, 2048)              0         
_________________________________________________________________
dense_2 (Dense)              (None, 2048)              4196352   
_________________________________________________________________
dropout_2 (Dropout)          (None, 2048)              0         
_________________________________________________________________
dense_3 (Dense)              (None, 101)               206949    
_________________________________________________________________
activation_1 (Activation)    (None, 101)               0         
=================================================================
Total params: 16,117,733
Trainable params: 16,117,733
Non-trainable params: 0
_________________________________________________________________
2019-03-14 10:46:39.491224: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2019-03-14 10:46:39.491251: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2019-03-14 10:46:39.491257: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2019-03-14 10:46:39.491261: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2019-03-14 10:46:39.491265: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ltroot/.local/lib/python3.5/site-packages/keras/utils/data_utils.py", line 568, in data_generator_task
    generator_output = next(self._generator)
  File "/ds_data/C3D-keras-master/train_c3d.py", line 117, in generator_train_batch
    x_train, x_labels = process_batch(new_line[a:b], img_path, train=True)
  File "/ds_data/C3D-keras-master/train_c3d.py", line 72, in process_batch
    img = imgs[symbol + j]
IndexError: list index out of range

Epoch 1/5
Traceback (most recent call last):
  File "/ds_data/C3D-keras-master/train_c3d.py", line 182, in <module>
    main()
  File "/ds_data/C3D-keras-master/train_c3d.py", line 173, in main
    verbose=1)
  File "/home/ltroot/.local/lib/python3.5/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/home/ltroot/.local/lib/python3.5/site-packages/keras/engine/training.py", line 2011, in fit_generator
    generator_output = next(output_generator)
StopIteration

Process finished with exit code 1
please look into this issue

**Comment by abhisheksurya578** [comment]
Using TensorFlow backend.

Layer (type) Output Shape Param #
input_1 (InputLayer) (None, 112, 112, 16, 3) 0

conv3d_1 (Conv3D) (None, 112, 112, 16, 64) 5248

max_pooling3d_1 (MaxPooling3 (None, 56, 56, 16, 64) 0

conv3d_2 (Conv3D) (None, 56, 56, 16, 128) 221312

max_pooling3d_2 (MaxPooling3 (None, 28, 28, 8, 128) 0

conv3d_3 (Conv3D) (None, 28, 28, 8, 128) 442496

max_pooling3d_3 (MaxPooling3 (None, 14, 14, 4, 128) 0

conv3d_4 (Conv3D) (None, 14, 14, 4, 256) 884992

max_pooling3d_4 (MaxPooling3 (None, 7, 7, 2, 256) 0

conv3d_5 (Conv3D) (None, 7, 7, 2, 256) 1769728

max_pooling3d_5 (MaxPooling3 (None, 4, 4, 1, 256) 0

flatten_1 (Flatten) (None, 4096) 0

dense_1 (Dense) (None, 2048) 8390656

dropout_1 (Dropout) (None, 2048) 0

dense_2 (Dense) (None, 2048) 4196352

dropout_2 (Dropout) (None, 2048) 0

dense_3 (Dense) (None, 101) 206949

activation_1 (Activation) (None, 101) 0
Total params: 16,117,733
Trainable params: 16,117,733
Non-trainable params: 0

2019-03-14 10:46:39.491224: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2019-03-14 10:46:39.491251: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2019-03-14 10:46:39.491257: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2019-03-14 10:46:39.491261: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2019-03-14 10:46:39.491265: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
Exception in thread Thread-1:
Traceback (most recent call last):
File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
self.run()
File "/usr/lib/python3.5/threading.py", line 862, in run
self._target(*self._args, **self._kwargs)
File "/home/ltroot/.local/lib/python3.5/site-packages/keras/utils/data_utils.py", line 568, in data_generator_task
generator_output = next(self._generator)
File "/ds_data/C3D-keras-master/train_c3d.py", line 117, in generator_train_batch
x_train, x_labels = process_batch(new_line[a:b], img_path, train=True)
File "/ds_data/C3D-keras-master/train_c3d.py", line 72, in process_batch
img = imgs[symbol + j]
IndexError: list index out of range

Epoch 1/5
Traceback (most recent call last):
File "/ds_data/C3D-keras-master/train_c3d.py", line 182, in 
main()
File "/ds_data/C3D-keras-master/train_c3d.py", line 173, in main
verbose=1)
File "/home/ltroot/.local/lib/python3.5/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
return func(*args, **kwargs)
File "/home/ltroot/.local/lib/python3.5/site-packages/keras/engine/training.py", line 2011, in fit_generator
generator_output = next(output_generator)
StopIteration

Process finished with exit code 1
please look into this issue
